### ISSUE TITLE
createProject project fails wit hPKIX path building failed.

### ISSUE THREAD

**Issue by nh13** [versioneye/versioneye_sbt_plugin#18]
I am getting an error when running `versioneye:createProject`.  Full output is below.  Thanks for any help in advance.

build.sbt
```
enablePlugins(VersionEyePlugin)
existingProjectId in versioneye := "57a1584c3d8eb6002dc1e812"
baseUrl in versioneye := "https://www.versioneye.com"
apiPath in versioneye := "/api/v2"
publishCrossVersion in versioneye := true
```

```
env | grep VERSIONEYE
VERSIONEYE_API_KEY=...
```

project/plugins.sbt
```
addSbtPlugin("com.versioneye" % "sbt-versioneye-plugin" % "0.2.0")
```

sbt output
```fgbio(master)> | 0.2.1-SNAPSHOT> versioneye:createProject
[info] .
[info] Starting to upload dependencies to https://www.versioneye.com. This can take a couple seconds ... 
[info] .
[trace] Stack trace suppressed: run last versioneye:createProject for the full output.
[error] (versioneye:createProject) javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] Total time: 1 s, completed Jun 23, 2017 9:20:34 AM
fgbio(master)> | 0.2.1-SNAPSHOT> last versioneye:createProject
[info] .
[info] Starting to upload dependencies to https://www.versioneye.com. This can take a couple seconds ... 
[info] .
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1250)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1248)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1247)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at scalaj.http.HttpRequest$$anonfun$8.apply(Http.scala:423)
	at scalaj.http.HttpRequest$$anonfun$8.apply(Http.scala:383)
	at scalaj.http.HttpRequest.exec(Http.scala:293)
	at scalaj.http.HttpRequest.execute(Http.scala:268)
	at scalaj.http.HttpRequest.asString(Http.scala:483)
	at com.versioneye.VersionEyePlugin$$anonfun$createTask$1.apply(VersionEyePlugin.scala:173)
	at com.versioneye.VersionEyePlugin$$anonfun$createTask$1.apply(VersionEyePlugin.scala:149)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by reiz** [comment]
Hi @nh13. At VersionEye we are using SSL certificates from [LetsEncrypt](https://letsencrypt.org). Older JVM versions don't support that. If you are using the Oracle JVM you need at least version 8u101. Please update your JVM to solve this problem and let us know if updating the JVM fixed the problem for you. /cc @mp911de

**Comment by reiz** [comment]
@nh13 Here is a link to StackOverflow which is related to this: https://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates.
